name: Example GitHub Action

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:

      - name: 21f3000591@ds.study.iitm.ac.in
        run: echo "Hello, world!"
