name: Example GitHub Action

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Run Custom Command
        run: echo "Hello, world!"

      - name: "21f3000591@ds.study.iitm.ac.in"
        run: echo "Step executed successfully!"
